### ISSUE TITLE
Remote Video (June)

### ISSUE THREAD

**Issue by ResilientSystemsLaboratory** [ResilientSystemsLaboratory/waffle-tx2#2]
We would like to be able to see the ZED camera over WiFi, as well as access other ros topics via WebSocket for debugging.

- [ ] Set up and test [rosbridge](https://wiki.ros.org/rosbridge_suite) on the Waffle TX2
- [x] Evaluate [web_video_server](http://wiki.ros.org/web_video_server)
- [ ] Develop a [tiny GTK+4 video stream application](https://developer.gnome.org/gtk4/stable/GtkMediaStream.html)
- [ ] Achieve acceptable video performance over 2.4 GHz WiFi

**Comment by NighttimeDriver50000** [comment]
web_video_server with MJPEG seems sufficient over WiFi. We can't really test rosbridge without a prototype application interfacing with it, which another developer is working on, so I'm closing this issue
